export const CONFIG_KEYS = {
  ENVIRONMENT: 'ENVIRONMENT',
  PORT: 'PORT',
  FRONTEND_LOCAL_URL: 'FRONTEND_LOCAL_URL',
  NODE_ENV: 'NODE_ENV',
  MONGODB_URI: 'MONGODB_URI',
  JWT_SECRET: 'JWT_SECRET'
} as const;
